/** Audit action names emitted by the backend (cti-backend/src/shared/strings.ts → AuditAction). */
export const AUDIT_ACTIONS = [
  'auth.login',
  'auth.login_failed',
  'auth.login_blocked',
  'auth.registered',
  'auth.password_changed',
  'auth.password_reset',
  'auth.refresh_reuse_detected',
  'user.invited',
  'user.updated',
  'user.deleted',
  'user.permissions_changed',
  'user.password_reset_issued',
  'user.sessions_revoked',
  'role.created',
  'role.updated',
  'role.deleted',
  'sync.requested',
  'asset.created',
  'asset.updated',
  'asset.deleted',
  'asset.imported',
  'vuln.status_changed',
  'vuln.rematched',
  'alert.channel_created',
  'alert.channel_updated',
  'alert.channel_deleted',
  'alert.rule_created',
  'alert.rule_updated',
  'alert.rule_deleted',
  'intel.watchlist_changed',
  'intel.indicator_changed',
  'report.schedule_changed',
  'report.generated',
] as const;
